In [191]:
# 梯度下降法(BGD,SGD,MSGD)python+numpy具体实现 参考链接: https://blog.csdn.net/pengjian444/article/details/71075544
# 机器学习中常见的最优化算法 参考链接: https://blog.csdn.net/wtq1993/article/details/51607040
# f(x,y)=(1−x)^2+100(y−x^2)^2  目标:求解最小值

In [176]:
import random
import numpy as np
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell


In [73]:
# #全部行都能输出
InteractiveShell.ast_node_interactivity = "all"

In [39]:
def cal_rosenbrock(x1=0.0, x2=0.0):
    """
    计算rosenbrock函数的值
    :param x1:
    :param x2:
    :return:
    """
    return (1 - x1) ** 2 + 100 * (x2 - x1 ** 2) ** 2

In [62]:
# 梯度下降方法求解最小值
def cal_partial_x(x1=0.0, x2=0.0):
    """
    对x求偏导
    """
    return 2 * (x1 - 1) + 400 * x1 * (x1 ** 2 - x2)

def cal_partial_y(x1, x2):
    """
    对x求偏导
    """
    return 200 * (x2 - x1 ** 2)


def gd_for_min(max_iter_count=100000, step_size=0.001):
    """
    梯度下降寻找最小值
    """
    # 初始化 x,y的值
    par_x = np.zeros((2,), dtype=np.float32)
    # 损失值
    loss = 10
    num_iter = 0
    while loss > 0.001 and num_iter < max_iter_count:
        # 如果损失大于0.001 并且迭代次数小于max_iter_count
        error = np.zeros((2,), dtype=np.float32)
        error[0] = cal_partial_x(par_x[0], par_x[1])
        error[1] = cal_partial_y(par_x[0], par_x[1])
        
        for i in range(len(par_x)):
            # 沿梯度的反方向更新par_x
            par_x[i] -= step_size * error[i]
        # 目标函数的最小值为0  所以带入原函数这个就是损失
        loss = cal_rosenbrock(par_x[0], par_x[1])
        if num_iter % 50 == 0:
            print("iter_count: ", num_iter, "the loss:", loss)
        num_iter += 1
    return par_x


    

In [63]:
# array([0.96840495, 0.9376793 ], dtype=float32)
gd_for_min()

iter_count:  0 the loss: 0.9960040014103906
iter_count:  50 the loss: 0.8173250023078208
iter_count:  100 the loss: 0.6787215496065403
iter_count:  150 the loss: 0.572809407603099
iter_count:  200 the loss: 0.49101944184659146
iter_count:  250 the loss: 0.4266009306452159
iter_count:  300 the loss: 0.3748012101126237
iter_count:  350 the loss: 0.33235324151747075
iter_count:  400 the loss: 0.29699262257045417
iter_count:  450 the loss: 0.2671196352393164
iter_count:  500 the loss: 0.2415783819389332
iter_count:  550 the loss: 0.21951566998896602
iter_count:  600 the loss: 0.20028837472778116
iter_count:  650 the loss: 0.18340317654635094
iter_count:  700 the loss: 0.1684749770814551
iter_count:  750 the loss: 0.15519886682400053
iter_count:  800 the loss: 0.14333008982436451
iter_count:  850 the loss: 0.13266987046080342
iter_count:  900 the loss: 0.12305516334901166
iter_count:  950 the loss: 0.11435083375122591
iter_count:  1000 the loss: 0.10644370829015032
iter_count:  1050 the los

array([0.96840495, 0.9376793 ], dtype=float32)

###  BGD（批量梯度下降法）

In [149]:
def gen_line_data(sample_num=100):
    """
    y = 3*x1 + 4*x2
    :return:
    """
    x1 = np.linspace(0, 9, sample_num)
    x2 = np.linspace(4, 13, sample_num)
    # x1, x2 搞成两列 相当于特征列 concatenate和vstack作用是一样的
    x = np.concatenate(([x1], [x2]), axis=0).T
    y = np.dot(x, np.array([3, 4]).T)  # y 列向量
    return x, y

In [76]:
x1 = np.array(range(8)).reshape(2, 4)
x2 = np.array(range(8, 16)).reshape(2, 4)
np.vstack((x1, x2))
np.stack([x1, x2], axis=-1)
np.stack([x1, x2], axis=1)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [83]:
x, y = gen_line_data()
df = pd.DataFrame(x)
df['y'] = y
df.head(10)

0         1          y
0  0.000000  4.000000  16.000000
1  0.090909  4.090909  16.636364
2  0.181818  4.181818  17.272727
3  0.272727  4.272727  17.909091
4  0.363636  4.363636  18.545455
5  0.454545  4.454545  19.181818
6  0.545455  4.545455  19.818182
7  0.636364  4.636364  20.454545
8  0.727273  4.727273  21.090909
9  0.818182  4.818182  21.727273

#### 线性回归的推导
![image](img/1.jpeg)

In [156]:
def bgd_for_min(samples, y, step_size=0.01, max_iter_count=10000):
    """
    批量梯度下降求sita (在demo中是w)
    """
    sample_num, dim = samples.shape
    w = np.zeros((dim,), dtype=np.float32)
    num_iter = 0
    loss = 10
    while loss > 0.001 and num_iter < max_iter_count:
        # 这个不能叫错误 准确来说是梯度向量
#         error = np.zeros((dim, ), dtype=np.float32)
        gradient = np.zeros((dim, ), dtype=np.float32)

        loss = 0
        # 遍历样本
        for i in range(sample_num):
            pred_y = np.dot(w, samples[i])
            for j in range(dim):
                gradient[j] += (y[i] - pred_y) * samples[i, j]
                
        for j in range(dim):
            w[j] += step_size * gradient[j] / sample_num
            
        for i in range(sample_num):
            pred_y = np.dot(w, samples[i])
            loss += (y[i] - pred_y) ** 2 
        loss = loss / sample_num
        if num_iter % 50 == 0:
            print("num_iter: ", num_iter, "the loss:", loss)
        num_iter += 1
    return w    

In [157]:
bgd_for_min(x, y)

num_iter:  0 the loss: 7.445309030387418
num_iter:  50 the loss: 0.12695212622054702
num_iter:  100 the loss: 0.044309058318090594
num_iter:  150 the loss: 0.015464655396450406
num_iter:  200 the loss: 0.0053973412421002755
num_iter:  250 the loss: 0.0018838139222933526


array([2.9735017, 4.015316 ], dtype=float32)

### SGB（随机梯度下降法）

In [162]:
# 构造线性回归数据
def gen_line_data(sample_num=100):
    """
    y = 3*x1 + 4*x2
    :return:
    """
    x1 = np.linspace(0, 9, sample_num)
    x2 = np.linspace(4, 13, sample_num)
    x = np.concatenate(([x1], [x2]), axis=0).T
    y = np.dot(x, np.array([3, 4]).T)  # y 列向量
    return x, y


In [163]:
x, y = gen_line_data()

#### 线性回归的推导
![image](img/2.png)

In [172]:
def sgd_for_min(samples, y, step_size=0.01, max_iter_count=10000):
    """
    随机梯度下降求参数
    """
    sample_num, dim = samples.shape
    loss = 10
    num_iter = 0
    w = np.zeros((dim, ), dtype=np.float32)
    while loss > 0.001 and num_iter < max_iter_count:
        loss = 0
        gradient = np.zeros((dim, ), dtype=np.float32)
        for i in range(sample_num):
            pred_y = np.dot(w, samples[i])
            for j in range(dim):
                gradient[j] += (y[i] - pred_y) * samples[i, j]
                w[j] += step_size * gradient[j] /sample_num
        for i in range(sample_num):
            pred_y = np.dot(w, samples[i])
            loss += (y[i] - pred_y) ** 2
        loss = loss / sample_num
#         if num_iter % 50 == 0:
#             print("num_iter: ", num_iter, "the loss:", loss)
        print("num_iter: ", num_iter, "the loss:", loss)

        num_iter += 1
    return w
    

In [173]:
sgd_for_min(x, y)

num_iter:  0 the loss: 899.5256395123043
num_iter:  1 the loss: 429.3892866487446
num_iter:  2 the loss: 139.34765711265553
num_iter:  3 the loss: 73.24721571797343
num_iter:  4 the loss: 21.75037765840998
num_iter:  5 the loss: 13.14228278589012
num_iter:  6 the loss: 3.530455803426953
num_iter:  7 the loss: 2.555822593919807
num_iter:  8 the loss: 0.6408691516613793
num_iter:  9 the loss: 0.5572900621999998
num_iter:  10 the loss: 0.1440751635975759
num_iter:  11 the loss: 0.1391997526762292
num_iter:  12 the loss: 0.041638116822024465
num_iter:  13 the loss: 0.039598945694037185
num_iter:  14 the loss: 0.014328956046269192
num_iter:  15 the loss: 0.012468114931806409
num_iter:  16 the loss: 0.005328085480538321
num_iter:  17 the loss: 0.004200748110832823
num_iter:  18 the loss: 0.002026801292554504
num_iter:  19 the loss: 0.0014756904896971385
num_iter:  20 the loss: 0.0007728594738228855


array([2.9770935, 4.012334 ], dtype=float32)

### MBGD(小批量梯度下降法)

In [174]:
# 构造线性数据
def gen_line_data(sample_num=100):
    """
    y = 3*x1 + 4*x2
    :return:
    """
    x1 = np.linspace(0, 9, sample_num)
    x2 = np.linspace(4, 13, sample_num)
    x = np.concatenate(([x1], [x2]), axis=0).T
    y = np.dot(x, np.array([3, 4]).T)  # y 列向量
    return x, y


In [175]:
x, y = gen_line_data()

In [189]:
def mbgd_for_min(samples, y, step_size=0.01, max_iter_count=10000, batch_size=0.2):
    """
    小批量梯度下降
    """
    sample_num, dim = samples.shape
    loss = 10
    num_iter = 0
    w = np.zeros((dim, ), dtype=np.float32)
    while loss > 0.001 and num_iter < max_iter_count:
        loss = 0
        # 每个特征对应的梯度
        gradient = np.zeros((dim, ), dtype=np.float32)
        # 每次从samples中随机抽取int(np.ceil(sample_num * batch_size))个数据, 返回索引数组
        sub_samples_index = random.sample(range(sample_num), int(np.ceil(sample_num * batch_size)))
        
        batch_samples = samples[sub_samples_index]
        batch_y = y[sub_samples_index]
        
        for i in range(len(batch_samples)):
            pred_y = np.dot(w, batch_samples[i])
            # 计算每个特征对应的梯度
            for j in range(dim):
                gradient[j] += (batch_y[i] - pred_y) * batch_samples[i, j]
        # 更新w, 
        for j in range(dim):
            w[j] += step_size * gradient[j] / sample_num
            
        for i in range(sample_num):
            pred_y = np.dot(w, samples[i])
            loss += (y[i] - pred_y) ** 2
        loss = loss / sample_num
        if num_iter % 50 == 0:
            print("num_iter: ", num_iter, "the loss:", loss)
        num_iter += 1
    return w

In [190]:
mbgd_for_min(x, y)

num_iter:  0 the loss: 1713.6820139059557
num_iter:  50 the loss: 0.2799037709046905
num_iter:  100 the loss: 0.23327767956244438
num_iter:  150 the loss: 0.18710766353661834
num_iter:  200 the loss: 0.15202963556430413
num_iter:  250 the loss: 0.1235119045090971
num_iter:  300 the loss: 0.10079747185001126
num_iter:  350 the loss: 0.08288594255328591
num_iter:  400 the loss: 0.06758127407031435
num_iter:  450 the loss: 0.05537068611119686
num_iter:  500 the loss: 0.04411088113527686
num_iter:  550 the loss: 0.03561444898750987
num_iter:  600 the loss: 0.028728431039987637
num_iter:  650 the loss: 0.023555662064661052
num_iter:  700 the loss: 0.018925377442524344
num_iter:  750 the loss: 0.015234254486513651
num_iter:  800 the loss: 0.012075845585857548
num_iter:  850 the loss: 0.009743275067814278
num_iter:  900 the loss: 0.007884798577751172
num_iter:  950 the loss: 0.006361021247143269
num_iter:  1000 the loss: 0.005259168491399806
num_iter:  1050 the loss: 0.004231007863105341
num_

array([2.9732964, 4.0154138], dtype=float32)