In [1]:
 # pip3 install watermark

In [2]:
%load_ext watermark

In [3]:
%watermark -a "jqc" -d -v -m -p numpy,pandas,matplotlib,scipy,sklearn

jqc 2019-03-21 

CPython 3.7.0
IPython 7.1.1

numpy 1.15.4
pandas 0.23.4
matplotlib 3.0.2
scipy 1.1.0
sklearn 0.20.0

compiler   : Clang 10.0.0 (clang-1000.11.45.5)
system     : Darwin
release    : 18.2.0
machine    : x86_64
processor  : i386
CPU cores  : 4
interpreter: 64bit


In [12]:
import numpy as np
import pandas as pd
from sklearn import naive_bayes, datasets, model_selection, metrics

In [6]:
# 手写数字识别集
digits = datasets.load_digits()
X, y = digits.data, digits.target
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.25, random_state=66)

In [7]:
gnb = naive_bayes.GaussianNB().fit(X_train, y_train)
gnb.score(X_test, y_test)

0.8488888888888889

In [14]:
pred = gnb.predict(X_test)
pred

array([8, 5, 8, 3, 3, 2, 5, 5, 0, 1, 7, 5, 1, 5, 7, 8, 0, 3, 7, 5, 1, 1,
       7, 0, 0, 0, 9, 0, 6, 9, 6, 1, 5, 5, 2, 5, 7, 2, 3, 5, 1, 7, 6, 6,
       2, 9, 1, 4, 5, 4, 4, 3, 1, 9, 4, 6, 4, 9, 0, 1, 6, 2, 3, 6, 3, 7,
       5, 6, 7, 8, 5, 1, 4, 0, 0, 2, 4, 1, 4, 3, 2, 1, 8, 7, 7, 6, 9, 0,
       2, 1, 8, 4, 5, 0, 6, 0, 4, 1, 2, 0, 5, 2, 4, 0, 0, 9, 3, 2, 6, 5,
       7, 8, 4, 6, 4, 8, 0, 8, 4, 6, 9, 7, 8, 2, 3, 5, 4, 9, 9, 1, 1, 0,
       7, 5, 3, 7, 9, 1, 0, 3, 1, 6, 4, 1, 6, 8, 7, 7, 7, 7, 8, 0, 1, 2,
       8, 7, 0, 3, 7, 9, 3, 1, 2, 0, 5, 0, 4, 2, 8, 8, 6, 4, 4, 9, 6, 0,
       8, 0, 7, 2, 1, 6, 9, 0, 4, 6, 2, 1, 2, 7, 9, 9, 6, 2, 6, 5, 2, 4,
       4, 5, 8, 5, 8, 1, 8, 4, 0, 8, 7, 7, 4, 4, 5, 4, 1, 0, 8, 7, 6, 9,
       6, 5, 0, 8, 2, 4, 6, 6, 8, 4, 4, 5, 8, 9, 4, 6, 4, 8, 0, 2, 4, 5,
       3, 9, 4, 8, 5, 5, 8, 7, 8, 6, 9, 8, 9, 3, 3, 1, 5, 0, 6, 9, 5, 5,
       9, 0, 0, 9, 6, 1, 5, 3, 0, 7, 9, 0, 5, 7, 0, 8, 2, 0, 3, 7, 6, 1,
       5, 6, 7, 3, 2, 4, 5, 9, 8, 3, 2, 6, 1, 5, 2,

In [9]:
# 预测在每个分类标签上的概率
gnb.predict_proba(X_test)

array([[4.62409934e-299, 1.22308911e-110, 4.86240758e-007, ...,
        0.00000000e+000, 9.99310374e-001, 1.47503369e-030],
       [6.32935001e-110, 1.49245093e-055, 1.37524550e-114, ...,
        0.00000000e+000, 1.25005597e-068, 1.81741137e-020],
       [1.44106385e-091, 4.99142310e-040, 1.52648669e-023, ...,
        5.08759054e-300, 9.98406304e-001, 1.59369525e-003],
       ...,
       [0.00000000e+000, 0.00000000e+000, 4.66791861e-032, ...,
        1.35407628e-015, 4.77001186e-018, 2.02667046e-033],
       [0.00000000e+000, 1.07253211e-064, 5.84833348e-085, ...,
        2.30049946e-011, 2.87707173e-024, 4.40008953e-041],
       [0.00000000e+000, 2.34969856e-052, 1.91843496e-167, ...,
        6.04359460e-021, 1.10944551e-060, 9.57272010e-141]])

In [10]:
gnb.predict_proba(X_test).shape

(450, 10)

In [11]:
gnb.class_count_

array([128., 131., 135., 143., 131., 130., 139., 142., 140., 128.])

In [15]:
# 使用混淆矩阵查看分类结果
metrics.confusion_matrix(y_test, pred)

array([[49,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0, 37,  1,  0,  0,  0,  1,  1,  5,  6],
       [ 0,  0, 27,  1,  0,  0,  1,  0, 13,  0],
       [ 0,  0,  2, 28,  0,  4,  0,  3,  2,  1],
       [ 0,  0,  0,  0, 47,  0,  1,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 49,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 42,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 37,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0, 30,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  7,  6, 36]])