In [26]:
import pandas as pd
import numpy as np
from gensim import corpora, models, similarities
from IPython.core.interactiveshell import InteractiveShell


In [27]:
# 配置项
%config IPCompleter.greedy=True


# #全部行都能输出
InteractiveShell.ast_node_interactivity = "all"

In [3]:
data = pd.read_csv('22.LDA_test.txt')
data

Human machine interface for lab abc computer applications
0  A survey of user opinion of computer system re...       
1           The EPS user interface management system       
2  System and human system engineering testing of...       
3  Relation of user perceived response time to er...       
4    The generation of random binary unordered trees       
5           The intersection graph of paths in trees       
6  Graph minors IV Widths of trees and well quasi...       
7                              Graph minors A survey

In [5]:
# 停止词
stop_list = set('for a of the and to in'.split())
stop_list

{'a', 'and', 'for', 'in', 'of', 'the', 'to'}

In [19]:
# 去停用词 把单词提取出来
data_texts = [[word for word in line.strip().lower().split(' ') 
               if word not in stop_list] 
              for line in data.iloc[:, 0]]
data_texts

[['survey', 'user', 'opinion', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'management', 'system'],
 ['system', 'human', 'system', 'engineering', 'testing', 'eps'],
 ['relation', 'user', 'perceived', 'response', 'time', 'error', 'measurement'],
 ['generation', 'random', 'binary', 'unordered', 'trees'],
 ['intersection', 'graph', 'paths', 'trees'],
 ['graph', 'minors', 'iv', 'widths', 'trees', 'well', 'quasi', 'ordering'],
 ['graph', 'minors', 'survey']]

In [34]:
dictionary = corpora.Dictionary(data_texts)
# 把单词转化成id
# dictionary.token2id
# 加载的文档数目
# dictionary.num_docs

In [36]:
corpus = [dictionary.doc2bow(line) for line in data_texts]
corpus

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1)],
 [(4, 1), (6, 1), (7, 1), (8, 1), (9, 1)],
 [(4, 2), (7, 1), (10, 1), (11, 1), (12, 1)],
 [(2, 1), (5, 1), (6, 1), (13, 1), (14, 1), (15, 1), (16, 1)],
 [(17, 1), (18, 1), (19, 1), (20, 1), (21, 1)],
 [(20, 1), (22, 1), (23, 1), (24, 1)],
 [(20, 1), (22, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1), (30, 1)],
 [(3, 1), (22, 1), (26, 1)]]

In [42]:
corpus_tfidf = models.TfidfModel(corpus)[corpus]
[* corpus_tfidf]


[[(0, 0.5144604839493077),
  (1, 0.5144604839493077),
  (2, 0.3429736559662051),
  (3, 0.3429736559662051),
  (4, 0.2426602922284707),
  (5, 0.3429736559662051),
  (6, 0.2426602922284707)],
 [(4, 0.27748680746253657),
  (6, 0.27748680746253657),
  (7, 0.39219710799742663),
  (8, 0.5882956619961399),
  (9, 0.5882956619961399)],
 [(4, 0.45312051966667244),
  (7, 0.32021802948515476),
  (10, 0.48032704422773215),
  (11, 0.48032704422773215),
  (12, 0.48032704422773215)],
 [(2, 0.2948764407342803),
  (5, 0.2948764407342803),
  (6, 0.20863061064644112),
  (13, 0.44231466110142054),
  (14, 0.44231466110142054),
  (15, 0.44231466110142054),
  (16, 0.44231466110142054)],
 [(17, 0.4866493367774363),
  (18, 0.4866493367774363),
  (19, 0.4866493367774363),
  (20, 0.22954235351308377),
  (21, 0.4866493367774363)],
 [(20, 0.30165504678093485),
  (22, 0.30165504678093485),
  (23, 0.6395343874660627),
  (24, 0.6395343874660627)],
 [(20, 0.19436180038939097),
  (22, 0.19436180038939097),
  (25, 0.4120

In [50]:
lsi = models.LsiModel(corpus=corpus_tfidf, num_topics=2, id2word=dictionary)
topic_result = [a for a in lsi[corpus_tfidf]]
topic_result
print('***' * 10)
lsi.print_topics(num_topics=2, num_words=5)
print('***' * 10)
list(similarities.MatrixSimilarity(corpus=lsi[corpus_tfidf]))

[[(0, 0.6704212442609235), (1, -0.22475722889302158)],
 [(0, 0.4274331981128131), (1, -0.4796826404094615)],
 [(0, 0.37344070191138057), (1, -0.4441824103440035)],
 [(0, 0.40055548254283047), (1, -0.258709267040433)],
 [(0, 0.07257140181557972), (1, 0.17078741700431108)],
 [(0, 0.26309641331220396), (1, 0.4404281053086908)],
 [(0, 0.38067944719848523), (1, 0.5684088459732185)],
 [(0, 0.5775696456050284), (1, 0.48577104473514676)]]

******************************


[(0,
  '0.401*"survey" + 0.316*"minors" + 0.303*"system" + 0.277*"graph" + 0.246*"user"'),
 (1,
  '0.349*"minors" + 0.347*"graph" + -0.293*"system" + -0.249*"eps" + 0.213*"trees"')]

******************************


[array([1.        , 0.86808664, 0.85344744, 0.96891284, 0.07825231,
        0.21335457, 0.263498  , 0.5210174 ], dtype=float32),
 array([ 0.86808664,  1.0000001 ,  0.9995862 ,  0.9639139 , -0.42696086,
        -0.2997726 , -0.25013044,  0.02857701], dtype=float32),
 array([ 8.5344744e-01,  9.9958622e-01,  1.0000000e+00,  9.5585704e-01,
        -4.5279664e-01, -3.2709184e-01, -2.7787879e-01, -1.8934038e-04],
       dtype=float32),
 array([ 0.96891284,  0.9639139 ,  0.95585704,  0.99999994, -0.17082398,
        -0.03498379,  0.01664756,  0.29365116], dtype=float32),
 array([ 0.07825231, -0.42696086, -0.45279664, -0.17082398,  1.        ,
         0.9906745 ,  0.9823212 ,  0.89169955], dtype=float32),
 array([ 0.21335457, -0.2997726 , -0.32709184, -0.03498379,  0.9906745 ,
         0.99999994,  0.99866694,  0.9450545 ], dtype=float32),
 array([ 0.263498  , -0.25013044, -0.2778788 ,  0.01664756,  0.9823212 ,
         0.99866694,  1.        ,  0.96066874], dtype=float32),
 array([ 5.2101737

In [49]:
num_topics = 2
lda = models.LdaModel(corpus=corpus_tfidf, 
                      num_topics=num_topics, 
                      id2word=dictionary, 
                      alpha='auto', 
                      eta='auto', 
                      minimum_probability=0.001)
[doc_t for doc_t in lda[corpus_tfidf]]
print('***' * 10)

[lda.show_topic(i) for i in range(num_topics)]
print('***' * 10)
list(similarities.MatrixSimilarity(corpus=lda[corpus_tfidf]))

[[(0, 0.25242853), (1, 0.74757147)],
 [(0, 0.609658), (1, 0.39034197)],
 [(0, 0.46594885), (1, 0.5340512)],
 [(0, 0.3039411), (1, 0.69605887)],
 [(0, 0.72621197), (1, 0.27378803)],
 [(0, 0.36687118), (1, 0.6331288)],
 [(0, 0.23214193), (1, 0.767858)],
 [(0, 0.26118717), (1, 0.7388128)]]

******************************


[[('eps', 0.040784054),
  ('random', 0.04042789),
  ('unordered', 0.03987739),
  ('generation', 0.039529156),
  ('binary', 0.03939213),
  ('user', 0.038381264),
  ('management', 0.038303025),
  ('trees', 0.03827824),
  ('interface', 0.037694685),
  ('system', 0.036862206)],
 [('survey', 0.04913843),
  ('minors', 0.04848479),
  ('graph', 0.04650354),
  ('system', 0.04326208),
  ('response', 0.037066963),
  ('time', 0.035821956),
  ('computer', 0.03430912),
  ('paths', 0.033761255),
  ('opinion', 0.0336728),
  ('intersection', 0.033445645)]]

******************************


[array([1.        , 0.7800468 , 0.92543435, 0.99628514, 0.6334311 ,
        0.980158  , 0.9994907 , 0.9998991 ], dtype=float32),
 array([0.7800468 , 0.99999994, 0.9589728 , 0.8310333 , 0.97828835,
        0.8885982 , 0.75968134, 0.78885597], dtype=float32),
 array([0.92543435, 0.9589728 , 1.        , 0.9546263 , 0.8793975 ,
        0.9821782 , 0.9128712 , 0.9307231 ], dtype=float32),
 array([0.99628514, 0.8310333 , 0.9546263 , 0.99999994, 0.697714  ,
        0.9935865 , 0.9930296 , 0.99740785], dtype=float32),
 array([0.6334311 , 0.97828835, 0.8793975 , 0.697714  , 0.99999994,
        0.77424335, 0.60841477, 0.6443584 ], dtype=float32),
 array([0.980158  , 0.8885982 , 0.9821782 , 0.9935865 , 0.77424335,
        1.        , 0.9733332 , 0.98287463], dtype=float32),
 array([0.9994907 , 0.75968134, 0.9128712 , 0.9930296 , 0.60841477,
        0.9733332 , 1.        , 0.99893653], dtype=float32),
 array([0.9998991 , 0.78885597, 0.9307231 , 0.99740785, 0.6443584 ,
        0.98287463, 0.9989365

In [54]:
hda = models.HdpModel(corpus=corpus, id2word=dictionary)
[doc_t for doc_t in hda[corpus_tfidf]]
print('***' * 10)
hda.print_topics(num_topics=2, num_words=5)

[[(0, 0.7913546653721194),
  (1, 0.05637515280199051),
  (2, 0.04343967587078447),
  (3, 0.029524966913848486),
  (4, 0.021522044447341397),
  (5, 0.01587412759775977),
  (6, 0.011743567843330745)],
 [(0, 0.7638512017021488),
  (1, 0.06365144319391157),
  (2, 0.04906350545933148),
  (3, 0.033481131713656805),
  (4, 0.024411132838698817),
  (5, 0.01800541039897691),
  (6, 0.013320274971539)],
 [(0, 0.5947980205151644),
  (1, 0.23741953221332474),
  (2, 0.04781625781641477),
  (3, 0.0325473884782397),
  (4, 0.023723730510435775),
  (5, 0.01749814138905409),
  (6, 0.012945000354836231)],
 [(0, 0.07985335962873226),
  (1, 0.055700338650282843),
  (2, 0.7563813869601043),
  (3, 0.029303661553427358),
  (4, 0.02137424566022493),
  (5, 0.015765204500429127),
  (6, 0.01166298855201405)],
 [(0, 0.5254037453063376),
  (1, 0.3052613419366467),
  (2, 0.047944779076514656),
  (3, 0.032920785297669994),
  (4, 0.024008610715561592),
  (5, 0.01770848104177841),
  (6, 0.013100610594038916)],
 [(0, 0.74

******************************


[(0,
  '0.115*eps + 0.071*unordered + 0.069*management + 0.056*generation + 0.054*survey'),
 (1,
  '0.170*ordering + 0.124*minors + 0.080*widths + 0.071*binary + 0.068*intersection')]