In [1]:
import numpy as np

In [23]:
def pca(x, k):
    x = np.array(x)
    mean = np.mean(x, axis=0)
    norm_x = x - mean
    # 因为是2个特征 最后形成的是2 * 2的方阵
    cov = np.dot(norm_x.T, norm_x)
    # 求协方差的特征值和特征向量
    eig_val, eig_vec = np.linalg.eig(cov)
    eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i]) for i in range(x.shape[1])]
    # 按照特征值 从大到小进行排序
    eig_pairs.sort(key=lambda x: x[0], reverse=True)
    # 拿出特征值最大所对应的向量 
    feature=np.array([ele[1] for ele in eig_pairs[:k]])
    
    data=np.dot(norm_x,np.transpose(feature))

    print (eig_val)
    print('\n')
    print(eig_vec)
    print('\n')
    print(eig_pairs)
    print('\n')
    print(feature)
    return data

In [25]:
x = np.array([[-1, 1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
pca(x, 1)

[37.7067455   1.62658783]


[[ 0.8549662  -0.51868371]
 [ 0.51868371  0.8549662 ]]


[(37.70674550364642, array([0.8549662 , 0.51868371])), (1.6265878296869243, array([-0.51868371,  0.8549662 ]))]


[[0.8549662  0.51868371]]


array([[-0.50917706],
       [-2.40151069],
       [-3.7751606 ],
       [ 1.20075534],
       [ 2.05572155],
       [ 3.42937146]])

In [26]:
from sklearn import decomposition

In [29]:
pca = decomposition.PCA(n_components=1)
pca.fit_transform(x)


array([[ 0.50917706],
       [ 2.40151069],
       [ 3.7751606 ],
       [-1.20075534],
       [-2.05572155],
       [-3.42937146]])

In [28]:
pca.explained_variance_

array([7.5413491])

In [30]:
pca.explained_variance_ratio_

array([0.95864607])